file=open('test.txt.','r+')
#data=file.read()
#data=file.readline()
#data=file.readlines()
data=file.write("im meraj bighamian\n")
print(file.tell())
file.seek(5)
file.write("hello")
#print(data)
file.close()